sudo: false
language: ruby
rvm:
  - ree
  - 1.9.3
  - 2.5.1
notifications:
  email: false
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
